blue "VX_UPSCALER_PATH is \"$VX_UPSCALER_PATH\""
blue "VX_UPSCALER_BINARY is \"$VX_UPSCALER_BINARY\""
blue "VX_UPSCALER_MODEL is \"$VX_UPSCALER_MODEL\""
blue "VX_UPSCALER_FACTOR is \"$VX_UPSCALER_FACTOR\""
inspect_args
